-- create users
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. A');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. B');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. C');

insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. D');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. E');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. F');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. G');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. H');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. I');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. J');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. K');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. L');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. M');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. N');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. O');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. P');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. Q');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. R');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. S');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. T');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. U');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. V');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. W');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. X');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. Y');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. Z');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. D');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. E');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. F');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. G');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. H');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. I');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. J');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. K');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. L');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. M');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. N');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. O');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. P');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. Q');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. R');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. S');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. T');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. U');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. V');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. W');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. X');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. Y');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. Z');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. D');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. E');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. F');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. G');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. H');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. I');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. J');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. K');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. L');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. M');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. N');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. O');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. P');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. Q');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. R');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. S');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. T');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. U');
insert into `user` (`email`, `name`) values ('a@ucla.edu', 'Mr. V');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. W');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. X');
insert into `user` (`email`, `name`) values ('b@ucla.edu', 'Mr. Y');
insert into `user` (`email`, `name`) values ('c@ucla.edu', 'Mr. Z');

-- create a lobby
insert into `lobby` (`maxUsers`, `gameTime`) values (3, 60);
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");
insert into `lobby` (`maxUsers`, `gameTime`, `state`) values (3, 60, "PUBLIC");

-- create players linked to those users
insert into `player` (`userId`, `lobbyId`) values (2, 1);
insert into `player` (`userId`, `lobbyId`) values (3, 1);
insert into `player` (`userId`, `lobbyId`) values (4, 1);
insert into `player` (`userId`, `lobbyId`) values (5, 2);
insert into `player` (`userId`, `lobbyId`) values (6, 3);
insert into `player` (`userId`, `lobbyId`) values (7, 4);
insert into `player` (`userId`, `lobbyId`) values (8, 5);
insert into `player` (`userId`, `lobbyId`) values (9, 6);
insert into `player` (`userId`, `lobbyId`) values (10, 7);
insert into `player` (`userId`, `lobbyId`) values (11, 8);
insert into `player` (`userId`, `lobbyId`) values (12, 9);
insert into `player` (`userId`, `lobbyId`) values (13, 10);
insert into `player` (`userId`, `lobbyId`) values (14, 11);
insert into `player` (`userId`, `lobbyId`) values (15, 12);
insert into `player` (`userId`, `lobbyId`) values (16, 13);
insert into `player` (`userId`, `lobbyId`) values (17, 14);
insert into `player` (`userId`, `lobbyId`) values (18, 15);
insert into `player` (`userId`, `lobbyId`) values (19, 16);
insert into `player` (`userId`, `lobbyId`) values (20, 17);
insert into `player` (`userId`, `lobbyId`) values (21, 18);
insert into `player` (`userId`, `lobbyId`) values (22, 19);
insert into `player` (`userId`, `lobbyId`) values (23, 20);
insert into `player` (`userId`, `lobbyId`) values (24, 21);
insert into `player` (`userId`, `lobbyId`) values (25, 22);
insert into `player` (`userId`, `lobbyId`) values (26, 23);
insert into `player` (`userId`, `lobbyId`) values (27, 24);
insert into `player` (`userId`, `lobbyId`) values (28, 25);
insert into `player` (`userId`, `lobbyId`) values (29, 26);
insert into `player` (`userId`, `lobbyId`) values (30, 27);
insert into `player` (`userId`, `lobbyId`) values (31, 28);
insert into `player` (`userId`, `lobbyId`) values (32, 29);
insert into `player` (`userId`, `lobbyId`) values (33, 30);
insert into `player` (`userId`, `lobbyId`) values (34, 31);
insert into `player` (`userId`, `lobbyId`) values (35, 32);
insert into `player` (`userId`, `lobbyId`) values (36, 33);
insert into `player` (`userId`, `lobbyId`) values (37, 34);
insert into `player` (`userId`, `lobbyId`) values (38, 35);
insert into `player` (`userId`, `lobbyId`) values (39, 36);
insert into `player` (`userId`, `lobbyId`) values (40, 37);
insert into `player` (`userId`, `lobbyId`) values (41, 38);
insert into `player` (`userId`, `lobbyId`) values (42, 39);
insert into `player` (`userId`, `lobbyId`) values (43, 40);
insert into `player` (`userId`, `lobbyId`) values (44, 41);
insert into `player` (`userId`, `lobbyId`) values (45, 42);
insert into `player` (`userId`, `lobbyId`) values (46, 43);
insert into `player` (`userId`, `lobbyId`) values (47, 44);
insert into `player` (`userId`, `lobbyId`) values (48, 45);
insert into `player` (`userId`, `lobbyId`) values (49, 46);
insert into `player` (`userId`, `lobbyId`) values (50, 47);
insert into `player` (`userId`, `lobbyId`) values (51, 48);
insert into `player` (`userId`, `lobbyId`) values (52, 49);
insert into `player` (`userId`, `lobbyId`) values (53, 50);
insert into `player` (`userId`, `lobbyId`) values (54, 51);
insert into `player` (`userId`, `lobbyId`) values (55, 52);
insert into `player` (`userId`, `lobbyId`) values (56, 53);
insert into `player` (`userId`, `lobbyId`) values (57, 54);
insert into `player` (`userId`, `lobbyId`) values (58, 55);
insert into `player` (`userId`, `lobbyId`) values (59, 56);
insert into `player` (`userId`, `lobbyId`) values (60, 57);
insert into `player` (`userId`, `lobbyId`) values (61, 58);
insert into `player` (`userId`, `lobbyId`) values (62, 59);
insert into `player` (`userId`, `lobbyId`) values (63, 60);
insert into `player` (`userId`, `lobbyId`) values (64, 61);
insert into `player` (`userId`, `lobbyId`) values (65, 62);
insert into `player` (`userId`, `lobbyId`) values (66, 63);
insert into `player` (`userId`, `lobbyId`) values (67, 64);
insert into `player` (`userId`, `lobbyId`) values (68, 65);
insert into `player` (`userId`, `lobbyId`) values (69, 66);
insert into `player` (`userId`, `lobbyId`) values (70, 67);
insert into `player` (`userId`, `lobbyId`) values (71, 68);
insert into `player` (`userId`, `lobbyId`) values (72, 69);
insert into `player` (`userId`, `lobbyId`) values (73, 70);

-- -- update users with FK
UPDATE user INNER JOIN player ON user.id = player.userId SET user.playerId = player.id;

-- make a tile and move
insert into `move` (`lobbyId`, `playerId`, `moveType`) values (1, 1, 'SpawnTiles');
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (0, 'A', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (1, 'B', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (2, 'C', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (3, 'D', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (4, 'E', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (5, 'F', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (6, 'G', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (7, 'H', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (8, 'I', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (9, 'J', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (10, 'K', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (11, 'L', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (12, 'M', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (13, 'N', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`) values (14, 'O', 1, 1);
insert into `tile` (`location`, `letter`, `value`, `moveId`, `tileType`) values (15, 'P', 1, 1, 'Dud');